language: php

dist: trusty

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../api_rest_gestion_des_entreprises --ignore=*/vendor/*